//! `/rpc/<命令名>` 路由表（票 08）。
//!
//! 每一项与 `src-tauri/src/startup.rs` 的 `tauri::generate_handler![...]` 一一对应：
//! 那边出 Tauri IPC 形态，这边出 HTTP 形态，**两张表必须是同一批命令**。
//!
//! 路由路径里的命令名不手写，由 [`rpc_last_seg`] 从路径末段 `stringify!` 出来 —— 路径写错
//! 编译不过，所以路径对了名字就一定对。漂移护栏（少写/多写一条）：
//! `node scripts/t08-rpc-names.mjs` 抽本文件的命令名集合，与 `scripts/t06-handler-names.mjs`
//! 抽的注册表逐行比对，必须零差集。
use axum::Router;
use axum::routing::post;

/// 取路径末段（= 命令名）。macro_rules 没有「取最后一个」，靠对尾部递归实现。
macro_rules! rpc_last_seg {
    ($a:ident) => { stringify!($a) };
    ($a:ident :: $($rest:ident)::+) => { rpc_last_seg!($($rest)::+) };
}

/// 把命令路径列表展开成 `.route("/rpc/<命令名>", post(<路径>::http))`。
macro_rules! rpc_routes {
    ($( $($seg:ident)::+ ),* $(,)?) => {
        /// 全部命令的 HTTP 路由。未登记的路径由 axum 自然落 404。
        ///
        /// 泛型在状态类型上：命令 handler 自己不吃 axum state（依赖走进程级 `AppCtx`），
        /// 所以本表能直接并进任何带 state 的 Router。
        pub fn rpc_router<S>() -> Router<S>
        where
            S: Clone + Send + Sync + 'static,
        {
            let mut r = Router::new();
            $(
                r = r.route(
                    &format!("/rpc/{}", rpc_last_seg!($($seg)::+)),
                    post($($seg)::+ :: http),
                );
            )*
            r
        }

        /// 本表登记的命令名（测试与自检用）。
        pub const RPC_COMMAND_NAMES: &[&str] = &[ $( rpc_last_seg!($($seg)::+) ),* ];
    };
}

rpc_routes! {
    aidog_core::platform_cmd::platform::platform_create,
    aidog_core::platform_cmd::platform::platform_list,
    aidog_core::platform_cmd::platform::platform_get,
    aidog_core::platform_cmd::platform::platform_share_export,
    aidog_core::platform_cmd::platform::platform_share_parse,
    aidog_core::platform_cmd::platform::platform_update,
    aidog_core::platform_cmd::platform::platform_delete,
    aidog_core::platform_cmd::platform::platform_purge_disabled,
    aidog_core::platform_cmd::platform::platform_purge_disabled_preview,
    aidog_core::platform_cmd::platform::platform_ensure_auto_group,
    aidog_core::platform_cmd::platform::platform_set_tray,
    aidog_core::platform_cmd::model_fetch::platform_fetch_models,
    aidog_core::platform_cmd::batch::batch_delete_platforms,
    aidog_core::platform_cmd::batch::batch_override_models,
    aidog_core::platform_cmd::batch::batch_set_status,
    aidog_core::platform_cmd::batch::batch_move_group,
    aidog_core::platform_cmd::platform::tray_config_get,
    aidog_core::platform_cmd::platform::tray_config_set,
    aidog_core::platform_cmd::platform::tray_today_stats,
    aidog_core::platform_cmd::stats::stats_query_batch,
    aidog_core::popover::popover_data,
    aidog_core::popover::popover_config_get,
    aidog_core::popover::popover_config_set,
    aidog_core::popover::popover_platform_today,
    aidog_core::platform_cmd::group::group_create,
    aidog_core::platform_cmd::group::group_list,
    aidog_core::platform_cmd::group::group_get,
    aidog_core::platform_cmd::group::group_update,
    aidog_core::platform_cmd::group::group_delete,
    aidog_core::platform_cmd::group::group_set_default,
    aidog_core::platform_cmd::group::group_set_platforms,
    aidog_core::platform_cmd::group::group_get_platforms,
    aidog_core::platform_cmd::group::group_detail,
    aidog_core::platform_cmd::group::group_detail_list,
    aidog_core::platform_cmd::group::group_detail_list_paged,
    aidog_core::platform_cmd::group::group_reorder,
    aidog_core::platform_cmd::group::group_platform_reorder,
    aidog_core::platform_cmd::group::group_platform_set_level_priority,
    aidog_core::platform_cmd::group::group_platform_move,
    aidog_core::platform_cmd::ui_extra::set_ui_extra,
    aidog_core::proxy_cmd::proxy::proxy_start,
    aidog_core::proxy_cmd::proxy::proxy_stop,
    aidog_core::proxy_cmd::proxy::proxy_status,
    aidog_core::proxy_cmd::proxy::proxy_get_settings,
    aidog_core::proxy_cmd::proxy::proxy_set_autostart,
    aidog_core::proxy_cmd::proxy::proxy_set_bind_lan,
    aidog_core::kernel_settings::kernel_settings_get,
    aidog_core::kernel_settings::kernel_settings_set,
    aidog_core::kernel_settings::kernel_set_bind_lan,
    aidog_core::proxy_cmd::proxy::app_set_autolaunch,
    aidog_core::proxy_cmd::proxy::app_get_autolaunch,
    aidog_core::proxy_cmd::proxy::app_set_silent_launch,
    aidog_core::proxy_cmd::proxy::proxy_client_get_settings,
    aidog_core::proxy_cmd::proxy::proxy_client_set_settings,
    aidog_core::sync_settings::export_claude_config,
    aidog_core::sync_settings::sync_group_settings,
    aidog_core::sync_settings::get_managed_paths,
    aidog_core::proxy_cmd::proxy_log::proxy_log_list,
    aidog_core::proxy_cmd::proxy_log::proxy_log_list_filtered,
    aidog_core::proxy_cmd::proxy_log::proxy_log_count_filtered,
    aidog_core::proxy_cmd::proxy_log::proxy_log_distinct_models,
    aidog_core::proxy_cmd::proxy_log::proxy_log_get,
    aidog_core::proxy_cmd::proxy_log::proxy_log_clear,
    aidog_core::proxy_cmd::proxy_log::proxy_log_count,
    aidog_core::proxy_cmd::proxy_log::proxy_log_settings_get,
    aidog_core::proxy_cmd::proxy_log::proxy_log_settings_set,
    aidog_core::proxy_cmd::proxy_log::proxy_log_cleanup_expired,
    aidog_core::proxy_cmd::proxy_log::proxy_log_cleanup_estimate,
    aidog_core::proxy_cmd::proxy_log::request_log_list,
    aidog_core::platform_cmd::stats::stats_settings_get,
    aidog_core::platform_cmd::stats::stats_settings_set,
    aidog_core::platform_cmd::stats::stats_rebuild_from_logs,
    aidog_backup::commands::db_compact,
    aidog_core::proxy_cmd::proxy_timeout::proxy_timeout_get,
    aidog_core::proxy_cmd::proxy_timeout::proxy_timeout_set,
    aidog_core::proxy_cmd::middleware::middleware_list_rules,
    aidog_core::proxy_cmd::middleware::middleware_create_rule,
    aidog_core::proxy_cmd::middleware::middleware_update_rule,
    aidog_core::proxy_cmd::middleware::middleware_delete_rule,
    aidog_core::proxy_cmd::middleware::middleware_settings_get,
    aidog_core::proxy_cmd::middleware::middleware_settings_set,
    aidog_core::system_cmd::scheduling::scheduling_settings_get,
    aidog_core::system_cmd::scheduling::scheduling_settings_set,
    aidog_core::system_cmd::notification::notification_settings_get,
    aidog_core::system_cmd::notification::notification_settings_set,
    aidog_core::system_cmd::notification::notification_inbox_list,
    aidog_core::system_cmd::notification::notification_clear,
    aidog_core::system_cmd::notification::notification_test,
    aidog_core::system_cmd::notification::notification_test_tts,
    aidog_core::system_cmd::notification::notification_test_popup,
    aidog_core::system_cmd::notification::notification_test_beep,
    aidog_core::hooks::inject_hooks,
    aidog_core::hooks::remove_hooks,
    aidog_core::hooks::get_default_hooks_enabled,
    aidog_core::hooks::set_default_hooks_enabled,
    aidog_core::hooks::build_notify_hooks_fragment,
    aidog_core::ai_tools_cmd::script_executor::check_uv,
    aidog_core::ai_tools_cmd::script_executor::install_uv,
    aidog_core::ai_tools_cmd::script_executor::set_script_executor,
    aidog_core::ai_tools_cmd::skills::skills_check_env,
    aidog_core::ai_tools_cmd::skills::skills_browse_catalog,
    aidog_core::ai_tools_cmd::skills::skills_search,
    aidog_core::ai_tools_cmd::skills::skills_list_installed,
    aidog_core::ai_tools_cmd::skills::skills_list_refresh,
    aidog_core::ai_tools_cmd::skills::skills_enable,
    aidog_core::ai_tools_cmd::skills::skills_install,
    aidog_core::ai_tools_cmd::skills::skill_detail,
    aidog_core::ai_tools_cmd::skills::skill_read_file,
    aidog_core::ai_tools_cmd::skills::skills_disable,
    aidog_core::ai_tools_cmd::skills::skills_update,
    aidog_core::ai_tools_cmd::skills::skills_uninstall_all,
    aidog_core::ai_tools_cmd::skills::skills_uninstall,
    aidog_core::ai_tools_cmd::skills::skills_install_batch,
    aidog_core::ai_tools_cmd::skills::skills_uninstall_batch,
    aidog_core::ai_tools_cmd::skills::skills_align_agents,
    aidog_core::ai_tools_cmd::skills::skills_enable_all,
    aidog_core::ai_tools_cmd::mcp::mcp_list,
    aidog_core::ai_tools_cmd::mcp::mcp_scan,
    aidog_core::ai_tools_cmd::mcp::mcp_import,
    aidog_core::ai_tools_cmd::mcp::mcp_import_json,
    aidog_core::ai_tools_cmd::mcp::mcp_set_agent,
    aidog_core::ai_tools_cmd::mcp::mcp_delete,
    aidog_core::ai_tools_cmd::mcp::mcp_update,
    aidog_core::ai_tools_cmd::mcp::mcp_add,
    aidog_core::ai_tools_cmd::mcp::mcp_resync,
    aidog_core::ai_tools_cmd::mcp::mcp_share_export,
    aidog_backup::commands::export_to_file,
    aidog_backup::commands::export_preview,
    aidog_backup::commands::backup_settings_get,
    aidog_backup::commands::backup_settings_set,
    aidog_backup::commands::backup_run_now,
    aidog_backup::commands::import_read_file,
    aidog_backup::commands::import_apply,
    aidog_backup::commands::ccswitch_detect,
    aidog_backup::commands::ccswitch_read,
    aidog_backup::commands::ccswitch_import,
    aidog_backup::commands::sub2api_parse,
    aidog_backup::commands::sub2api_read_file,
    aidog_backup::commands::sub2api_import,
    aidog_core::system_cmd::app_log::app_log_settings_get,
    aidog_core::system_cmd::app_log::app_log_settings_set,
    aidog_core::system_cmd::auto_update::get_auto_update_enabled,
    aidog_core::system_cmd::auto_update::set_auto_update_enabled,
    aidog_core::ai_tools_cmd::coding_tools::coding_tools_settings_get,
    aidog_core::ai_tools_cmd::coding_tools::coding_tools_settings_set,
    aidog_core::system_cmd::fs_autocomplete::fs_autocomplete,
    aidog_core::settings::settings_get,
    aidog_core::settings::settings_set,
    aidog_core::settings::settings_delete,
    aidog_core::settings::settings_list,
    aidog_core::settings::generate_statusline_script,
    aidog_core::settings::read_claude_code_settings,
    aidog_core::gateway::codex::codex_config_read,
    aidog_core::gateway::codex::codex_config_write,
    aidog_core::gateway::codex::codex_config_path,
    aidog_core::gateway::pi::pi_models_path,
    aidog_core::gateway::pi::pi_settings_read,
    aidog_core::gateway::pi::pi_settings_write,
    aidog_core::platform_cmd::stats::stats_query,
    aidog_core::ai_tools_cmd::model_test::model_test,
    aidog_core::proxy_cmd::proxy_log::platform_usage_stats,
    aidog_core::proxy_cmd::proxy_log::group_usage_stats,
    aidog_core::proxy_cmd::proxy_log::all_group_usage_stats,
    aidog_core::proxy_cmd::proxy_log::all_platform_usage_stats,
    aidog_core::proxy_cmd::proxy_log::get_last_test_result,
    aidog_core::platform_cmd::quota::platform_query_quota,
    aidog_core::platform_cmd::quota::platform_query_quota_newapi,
    aidog_core::platform_cmd::quota::platform_query_quota_devin,
    aidog_core::platform_cmd::platform::platform_reorder,
    aidog_cli_proxy::provider::cli_proxy_list,
    aidog_cli_proxy::provider::cli_proxy_get,
    aidog_cli_proxy::provider::cli_proxy_create,
    aidog_cli_proxy::provider::cli_proxy_update,
    aidog_cli_proxy::provider::cli_proxy_delete,
    aidog_cli_proxy::test_cmd::cli_proxy_test,
    aidog_cli_proxy::platform::create_cli_proxy_platform,
    aidog_cli_proxy::import::cli_proxy_import,
    aidog_cli_proxy::batch::batch_delete_cli_proxy_providers,
    aidog_cli_proxy::batch::batch_override_cli_proxy_models,
    aidog_cli_proxy::batch::batch_set_cli_proxy_quota,
    aidog_core::platform_cmd::price::model_price_sync,
    aidog_core::platform_cmd::price::price_sync_settings_get,
    aidog_core::platform_cmd::price::price_sync_settings_set,
    aidog_core::platform_cmd::model_entry::model_entry_list,
    aidog_core::platform_cmd::model_entry::model_entry_get,
    aidog_core::platform_cmd::model_entry::model_info_snapshot,
    aidog_core::system_cmd::about::about_info,
    aidog_core::cli_env::cli_check_versions,
    aidog_core::cli_env::cli_install,
    aidog_core::cli_env::cli_upgrade,
    aidog_core::cli_env::cli_diagnose_conflicts,
    aidog_core::cli_env::cli_check_updates,
    aidog_core::defaults::get_defaults_json,
    aidog_core::defaults::get_protocol_logo_path,
    aidog_core::defaults::sync_protocol_logo,
    aidog_core::defaults::get_client_types_json,
    aidog_core::proxy_cmd::mitm::mitm_status,
    aidog_core::proxy_cmd::mitm::mitm_enable,
    aidog_core::proxy_cmd::mitm::mitm_disable,
    aidog_core::proxy_cmd::mitm::mitm_install_ca_prepare,
    aidog_core::proxy_cmd::mitm::mitm_uninstall_ca_prepare,
    aidog_core::proxy_cmd::mitm::mitm_set_ca_installed,
    aidog_core::proxy_cmd::mitm::mitm_classify_trust_error,
    aidog_core::proxy_cmd::mitm::mitm_whitelist_add,
    aidog_core::proxy_cmd::mitm::mitm_whitelist_remove,
    aidog_core::proxy_cmd::mitm::mitm_whitelist_toggle,
    aidog_core::proxy_cmd::mitm::mitm_whitelist_import_defaults,
    aidog_core::proxy_cmd::mitm::mitm_whitelist_clear,
    aidog_core::proxy_cmd::mitm::mitm_whitelist_test_url,
    aidog_core::proxy_cmd::mitm::mitm_reset_suspects,
}
